import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Lang = 'English (US)' | 'Spanish' | 'French' | 'German' | 'Hindi';

interface TranslationDict {
  [key: string]: string;
}

const dictionaries: Record<Lang, TranslationDict> = {
  'English (US)': {
    dashboard: 'Dashboard',
    uploadPaper: 'Upload Paper',
    library: 'Library',
    semanticSearch: 'Semantic Search',
    aiChat: 'AI Chat',
    settings: 'Settings',
    support: 'Support',
    researchLibrary: 'Research Library',
    managePapers: 'Manage and access your uploaded research papers.',
    uploadNew: 'Upload New',
    searchPlaceholder: 'Search by title, author, or keywords...',
    filters: 'Filters',
    noPapers: 'No papers found',
    noPapersHint: 'Try adjusting your search or upload a new paper.',
    untitled: 'Untitled',
    unknownAuthor: 'Unknown Author',
    analyze: 'Analyze',
    viewDocument: 'View Document',
    downloadPDF: 'Download PDF',
    deletePaper: 'Delete Paper',
    paperTitle: 'Paper Title',
    authors: 'Authors',
    year: 'Year',
    uploadDate: 'Upload Date',
    actions: 'Actions',
    appPreferences: 'App Preferences',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Switch between light and dark themes.',
    compactView: 'Compact View',
    compactViewDesc: 'Reduce spacing and card sizes for a denser layout.',
    autoAnalyze: 'Auto-Analyze on Upload',
    autoAnalyzeDesc: 'Automatically run AI analysis when a document is uploaded.',
    language: 'Language',
    languageDesc: 'Select your preferred display language.',
    savePreferences: 'Save Preferences',
    preferencesSaved: 'Preferences saved!',
    compareDocuments: 'Compare Documents',
    compareDesc: 'Select research papers to generate an AI-powered comparative analysis.',
    selectDocuments: 'Select Documents',
    maxCompareHint: 'Select 2–5 documents',
    selectAtLeastTwo: 'Select at least 2 documents to compare',
    comparing: 'Comparing...',
    comparisonComplete: 'Comparison complete',
    comparisonFailed: 'Comparison failed',
    comparisonResults: 'Comparison Results',
    summary: 'Summary',
    commonThemes: 'Common Themes',
    conflictingFindings: 'Conflicting Findings',
    researchGaps: 'Research Gaps',
    novelOpportunities: 'Novel Opportunities',
    comparisonTable: 'Comparison Table',
    featureComparison: 'Feature Comparison',
    aiGenerated: 'AI Generated',
    heuristicResults: 'Heuristic',
    noDocumentsToCompare: 'No documents available to compare.',
    clearSelection: 'Clear',
    selected: 'selected',
    compare: 'Compare',
    recompare: 'Run again',
    noSummary: 'No summary available.',
    maxSelectionReached: 'You can compare up to 5 documents at a time',
    dimension: 'Dimension',
    paperA: 'Paper A',
    paperB: 'Paper B',    comparison: 'Comparison',
    compareSelected: 'Compare Selected',
    newSession: 'New Session',
    navigate: 'Navigate',
    recentPapers: 'Recent Papers',
    viewAll: 'View All',
    totalPapers: 'Total Papers',
    aiAnalyses: 'AI Analyses',
    quickActions: 'Quick Actions',
  },
  Spanish: {
    dashboard: 'Panel',
    uploadPaper: 'Subir Documento',
    library: 'Biblioteca',
    semanticSearch: 'Búsqueda Semántica',
    aiChat: 'Chat IA',
    settings: 'Configuración',
    support: 'Soporte',
    researchLibrary: 'Biblioteca de Investigación',
    managePapers: 'Gestiona y accede a tus documentos de investigación.',
    uploadNew: 'Subir Nuevo',
    searchPlaceholder: 'Buscar por título, autor o palabras clave...',
    filters: 'Filtros',
    noPapers: 'No se encontraron documentos',
    noPapersHint: 'Intenta ajustar tu búsqueda o sube un nuevo documento.',
    untitled: 'Sin título',
    unknownAuthor: 'Autor desconocido',
    analyze: 'Analizar',
    viewDocument: 'Ver Documento',
    downloadPDF: 'Descargar PDF',
    deletePaper: 'Eliminar Documento',
    paperTitle: 'Título',
    authors: 'Autores',
    year: 'Año',
    uploadDate: 'Fecha de subida',
    actions: 'Acciones',
    appPreferences: 'Preferencias de la Aplicación',
    darkMode: 'Modo Oscuro',
    darkModeDesc: 'Cambia entre temas claro y oscuro.',
    compactView: 'Vista Compacta',
    compactViewDesc: 'Reduce el espaciado y el tamaño de las tarjetas.',
    autoAnalyze: 'Auto-Analizar al Subir',
    autoAnalyzeDesc: 'Ejecuta automáticamente el análisis de IA al subir un documento.',
    language: 'Idioma',
    languageDesc: 'Selecciona tu idioma de visualización preferido.',
    savePreferences: 'Guardar Preferencias',
    preferencesSaved: '¡Preferencias guardadas!',
    compareDocuments: 'Comparar Documentos',
    compareDesc: 'Seleccione documentos de investigación para generar un análisis comparativo impulsado por IA.',
    selectDocuments: 'Seleccionar Documentos',
    maxCompareHint: 'Seleccione 2–5 documentos',
    selectAtLeastTwo: 'Seleccione al menos 2 documentos para comparar',
    comparing: 'Comparando...',
    comparisonComplete: 'Comparación completa',
    comparisonFailed: 'La comparación falló',
    comparisonResults: 'Resultados de la Comparación',
    summary: 'Resumen',
    commonThemes: 'Temas Comunes',
    conflictingFindings: 'Hallazgos Conflictivos',
    researchGaps: 'Vacíos de Investigación',
    novelOpportunities: 'Oportunidades Novedosas',
    comparisonTable: 'Tabla Comparativa',
    featureComparison: 'Comparación de Características',
    aiGenerated: 'Generado por IA',
    heuristicResults: 'Heurístico',
    noDocumentsToCompare: 'No hay documentos disponibles para comparar.',
    clearSelection: 'Limpiar',
    selected: 'seleccionado',
    compare: 'Comparar',
    recompare: 'Ejecutar de nuevo',
    noSummary: 'No hay resumen disponible.',
    maxSelectionReached: 'Puede comparar hasta 5 documentos a la vez',
    dimension: 'Dimensión',
    paperA: 'Documento A',
    paperB: 'Documento B',
    comparison: 'Comparación',
    compareSelected: 'Comparar Seleccionados',
    newSession: 'Nueva Sesión',
    navigate: 'Navegar',
    recentPapers: 'Documentos Recientes',
    viewAll: 'Ver Todo',
    totalPapers: 'Total de Documentos',
    aiAnalyses: 'Análisis de IA',
    quickActions: 'Acciones Rápidas',
  },
  French: {
    dashboard: 'Tableau de Bord',
    uploadPaper: 'Télécharger',
    library: 'Bibliothèque',
    semanticSearch: 'Recherche Sémantique',
    aiChat: 'Chat IA',
    settings: 'Paramètres',
    support: 'Support',
    researchLibrary: 'Bibliothèque de Recherche',
    managePapers: 'Gérez et accédez à vos documents de recherche.',
    uploadNew: 'Nouveau Téléchargement',
    searchPlaceholder: 'Rechercher par titre, auteur ou mots-clés...',
    filters: 'Filtres',
    noPapers: 'Aucun document trouvé',
    noPapersHint: 'Essayez d\'ajuster votre recherche ou téléchargez un nouveau document.',
    untitled: 'Sans titre',
    unknownAuthor: 'Auteur inconnu',
    analyze: 'Analyser',
    viewDocument: 'Voir le Document',
    downloadPDF: 'Télécharger le PDF',
    deletePaper: 'Supprimer le Document',
    paperTitle: 'Titre',
    authors: 'Auteurs',
    year: 'Année',
    uploadDate: 'Date de téléchargement',
    actions: 'Actions',
    appPreferences: 'Préférences de l\'Application',
    darkMode: 'Mode Sombre',
    darkModeDesc: 'Basculer entre les thèmes clair et sombre.',
    compactView: 'Vue Compacte',
    compactViewDesc: 'Réduire l\'espacement et la taille des cartes.',
    autoAnalyze: 'Analyse Auto au Téléchargement',
    autoAnalyzeDesc: 'Lancer automatiquement l\'analyse IA lors du téléchargement.',
    language: 'Langue',
    languageDesc: 'Sélectionnez votre langue d\'affichage préférée.',
    savePreferences: 'Enregistrer les Préférences',
    preferencesSaved: 'Préférences enregistrées !',
    compareDocuments: 'Comparer les Documents',
    compareDesc: 'Sélectionnez des documents de recherche pour générer une analyse comparative alimentée par l\'IA.',
    selectDocuments: 'Sélectionner des Documents',
    maxCompareHint: 'Sélectionnez 2 à 5 documents',
    selectAtLeastTwo: 'Sélectionnez au moins 2 documents à comparer',
    comparing: 'Comparaison en cours...',
    comparisonComplete: 'Comparaison terminée',
    comparisonFailed: 'La comparaison a échoué',
    comparisonResults: 'Résultats de la Comparaison',
    summary: 'Résumé',
    commonThemes: 'Thèmes Communs',
    conflictingFindings: 'Conclusions Contradictoires',
    researchGaps: 'Lacunes de Recherche',
    novelOpportunities: 'Opportunités Nouvelles',
    comparisonTable: 'Tableau Comparatif',
    featureComparison: 'Comparaison des Caractéristiques',
    aiGenerated: 'Généré par IA',
    heuristicResults: 'Heuristique',
    noDocumentsToCompare: 'Aucun document disponible pour la comparaison.',
    clearSelection: 'Effacer',
    selected: 'sélectionné',
    compare: 'Comparer',
    recompare: 'Relancer',
    noSummary: 'Aucun résumé disponible.',
    maxSelectionReached: 'Vous pouvez comparer jusqu\'à 5 documents à la fois',
    dimension: 'Dimension',
    paperA: 'Document A',
    paperB: 'Document B',
    comparison: 'Comparaison',
    compareSelected: 'Comparer la Sélection',
    newSession: 'Nouvelle Session',
    navigate: 'Naviguer',
    recentPapers: 'Documents Récents',
    viewAll: 'Voir Tout',
    totalPapers: 'Total des Documents',
    aiAnalyses: 'Analyses IA',
    quickActions: 'Actions Rapides',
  },
  German: {
    dashboard: 'Dashboard',
    uploadPaper: 'Dokument Hochladen',
    library: 'Bibliothek',
    semanticSearch: 'Semantische Suche',
    aiChat: 'KI-Chat',
    settings: 'Einstellungen',
    support: 'Support',
    researchLibrary: 'Forschungsbibliothek',
    managePapers: 'Verwalten und greifen Sie auf Ihre hochgeladenen Forschungsarbeiten zu.',
    uploadNew: 'Neu Hochladen',
    searchPlaceholder: 'Suche nach Titel, Autor oder Schlüsselwörtern...',
    filters: 'Filter',
    noPapers: 'Keine Dokumente gefunden',
    noPapersHint: 'Passen Sie Ihre Suche an oder laden Sie ein neues Dokument hoch.',
    untitled: 'Ohne Titel',
    unknownAuthor: 'Unbekannter Autor',
    analyze: 'Analysieren',
    viewDocument: 'Dokument Ansehen',
    downloadPDF: 'PDF Herunterladen',
    deletePaper: 'Dokument Löschen',
    paperTitle: 'Titel',
    authors: 'Autoren',
    year: 'Jahr',
    uploadDate: 'Upload-Datum',
    actions: 'Aktionen',
    appPreferences: 'App-Einstellungen',
    darkMode: 'Dunkelmodus',
    darkModeDesc: 'Zwischen hellem und dunklem Thema wechseln.',
    compactView: 'Kompaktansicht',
    compactViewDesc: 'Abstände und Kartengrößen für eine dichtere Ansicht reduzieren.',
    autoAnalyze: 'Auto-Analyse beim Hochladen',
    autoAnalyzeDesc: 'Automatisch KI-Analyse beim Hochladen eines Dokuments ausführen.',
    language: 'Sprache',
    languageDesc: 'Wählen Sie Ihre bevorzugte Anzeigesprache.',
    savePreferences: 'Einstellungen Speichern',
    preferencesSaved: 'Einstellungen gespeichert!',
    compareDocuments: 'Dokumente Vergleichen',
    compareDesc: 'Wählen Sie Forschungsdokumente aus, um eine KI-gestützte vergleichende Analyse zu erstellen.',
    selectDocuments: 'Dokumente Auswählen',
    maxCompareHint: 'Wählen Sie 2–5 Dokumente',
    selectAtLeastTwo: 'Wählen Sie mindestens 2 Dokumente zum Vergleichen aus',
    comparing: 'Vergleiche...',
    comparisonComplete: 'Vergleich abgeschlossen',
    comparisonFailed: 'Vergleich fehlgeschlagen',
    comparisonResults: 'Vergleichsergebnisse',
    summary: 'Zusammenfassung',
    commonThemes: 'Gemeinsame Themen',
    conflictingFindings: 'Widersprüchliche Ergebnisse',
    researchGaps: 'Forschungslücken',
    novelOpportunities: 'Neue Möglichkeiten',
    comparisonTable: 'Vergleichstabelle',
    featureComparison: 'Merkmalsvergleich',
    aiGenerated: 'KI-Generiert',
    heuristicResults: 'Heuristisch',
    noDocumentsToCompare: 'Keine Dokumente zum Vergleichen verfügbar.',
    clearSelection: 'Auswahl löschen',
    selected: 'ausgewählt',
    compare: 'Vergleichen',
    recompare: 'Erneut ausführen',
    noSummary: 'Keine Zusammenfassung verfügbar.',
    maxSelectionReached: 'Sie können bis zu 5 Dokumente gleichzeitig vergleichen',
    dimension: 'Dimension',
    paperA: 'Dokument A',
    paperB: 'Dokument B',
    comparison: 'Vergleich',
    compareSelected: 'Auswahl Vergleichen',
    newSession: 'Neue Sitzung',
    navigate: 'Navigieren',
    recentPapers: 'Aktuelle Dokumente',
    viewAll: 'Alle anzeigen',
    totalPapers: 'Gesamt Dokumente',
    aiAnalyses: 'KI-Analysen',
    quickActions: 'Schnellaktionen',
  },
  Hindi: {
    dashboard: 'डैशबोर्ड',
    uploadPaper: 'दस्तावेज़ अपलोड करें',
    library: 'पुस्तकालय',
    semanticSearch: 'सिमेंटिक खोज',
    aiChat: 'एआई चैट',
    settings: 'सेटिंग्स',
    support: 'सहायता',
    researchLibrary: 'अनुसंधान पुस्तकालय',
    managePapers: 'अपने अपलोड किए गए शोध पत्रों को प्रबंधित और एक्सेस करें।',
    uploadNew: 'नया अपलोड करें',
    searchPlaceholder: 'शीर्षक, लेखक या कीवर्ड से खोजें...',
    filters: 'फ़िल्टर',
    noPapers: 'कोई दस्तावेज़ नहीं मिला',
    noPapersHint: 'अपनी खोज को समायोजित करें या एक नया दस्तावेज़ अपलोड करें।',
    untitled: 'बिना शीर्षक',
    unknownAuthor: 'अज्ञात लेखक',
    analyze: 'विश्लेषण करें',
    viewDocument: 'दस्तावेज़ देखें',
    downloadPDF: 'PDF डाउनलोड करें',
    deletePaper: 'दस्तावेज़ हटाएँ',
    paperTitle: 'शीर्षक',
    authors: 'लेखक',
    year: 'वर्ष',
    uploadDate: 'अपलोड की तारीख',
    actions: 'कार्रवाइयाँ',
    appPreferences: 'ऐप वरीयताएँ',
    darkMode: 'डार्क मोड',
    darkModeDesc: 'हल्के और गहरे थीम के बीच स्विच करें।',
    compactView: 'कॉम्पैक्ट दृश्य',
    compactViewDesc: 'घनी लेआउट के लिए स्पेसिंग और कार्ड आकार कम करें।',
    autoAnalyze: 'अपलोड पर ऑटो-विश्लेषण',
    autoAnalyzeDesc: 'दस्तावेज़ अपलोड होने पर स्वचालित रूप से AI विश्लेषण चलाएँ।',
    language: 'भाषा',
    languageDesc: 'अपनी पसंदीदा प्रदर्शन भाषा चुनें।',
    savePreferences: 'वरीयताएँ सहेजें',
    preferencesSaved: 'वरीयताएँ सहेजी गईं!',
    compareDocuments: 'दस्तावेज़ तुलना करें',
    compareDesc: 'AI-संचालित तुलनात्मक विश्लेषण उत्पन्न करने के लिए शोध पत्र चुनें।',
    selectDocuments: 'दस्तावेज़ चुनें',
    maxCompareHint: '2–5 दस्तावेज़ चुनें',
    selectAtLeastTwo: 'तुलना करने के लिए कम से कम 2 दस्तावेज़ चुनें',
    comparing: 'तुलना हो रही है...',
    comparisonComplete: 'तुलना पूर्ण',
    comparisonFailed: 'तुलना विफल हुई',
    comparisonResults: 'तुलना परिणाम',
    summary: 'सारांश',
    commonThemes: 'सामान्य विषय',
    conflictingFindings: 'विरोधाभासी निष्कर्ष',
    researchGaps: 'शोध अंतराल',
    novelOpportunities: 'नवीन अवसर',
    comparisonTable: 'तुलना तालिका',
    featureComparison: 'विशेषता तुलना',
    aiGenerated: 'AI-जनित',
    heuristicResults: 'ह्यूरिस्टिक',
    noDocumentsToCompare: 'तुलना के लिए कोई दस्तावेज़ उपलब्ध नहीं हैं।',
    clearSelection: 'साफ़ करें',
    selected: 'चयनित',
    compare: 'तुलना करें',
    recompare: 'फिर से चलाएँ',
    noSummary: 'कोई सारांश उपलब्ध नहीं।',
    maxSelectionReached: 'आप एक बार में अधिकतम 5 दस्तावेज़ों की तुलना कर सकते हैं',
    dimension: 'आयाम',
    paperA: 'दस्तावेज़ A',
    paperB: 'दस्तावेज़ B',
    comparison: 'तुलना',
    compareSelected: 'चयनित की तुलना करें',
    newSession: 'नया सत्र',
    navigate: 'नेविगेट करें',
    recentPapers: 'हाल के दस्तावेज़',
    viewAll: 'सभी देखें',
    totalPapers: 'कुल दस्तावेज़',
    aiAnalyses: 'एआई विश्लेषण',
    quickActions: 'त्वरित कार्रवाई',
  },
};

interface LanguageContextValue {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'English (US)',
  setLanguage: () => {},
  t: (key: string) => key,
});

const LANG_KEY = 'scholarai_language';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Lang>(() => {
    const stored = localStorage.getItem(LANG_KEY);
    return (stored as Lang) || 'English (US)';
  });

  const setLanguage = useCallback((lang: Lang) => {
    localStorage.setItem(LANG_KEY, lang);
    setLanguageState(lang);
  }, []);

  const t = useCallback(
    (key: string) => {
      return dictionaries[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

