import React, { createContext, useContext, useCallback } from 'react';
import { useAppStore, AppLanguage } from '../store/useAppStore';

interface TranslationDict {
  [key: string]: string;
}

const dictionaries: Record<AppLanguage, TranslationDict> = {
  'English (US)': {
    dashboard: 'Dashboard',
    uploadPaper: 'Upload Paper',
    library: 'Library',
    semanticSearch: 'Semantic Search',
    aiChat: 'AI Chat',
    settings: 'Settings',
    support: 'Support',
    researchLibrary: 'Research Library',
    managePapers: 'Manage and access your uploaded research papers.',
    uploadNew: 'Upload New',
    searchPlaceholder: 'Search by title, author, or keywords...',
    filters: 'Filters',
    noPapers: 'No papers found',
    noPapersHint: 'Try adjusting your search or upload a new paper.',
    untitled: 'Untitled',
    unknownAuthor: 'Unknown Author',
    analyze: 'Analyze',
    viewDocument: 'View Document',
    downloadPDF: 'Download PDF',
    deletePaper: 'Delete Paper',
    paperTitle: 'Paper Title',
    authors: 'Authors',
    year: 'Year',
    uploadDate: 'Upload Date',
    actions: 'Actions',
    appPreferences: 'App Preferences',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Switch between light and dark themes.',
    compactView: 'Compact View',
    compactViewDesc: 'Reduce spacing and card sizes for a denser layout.',
    autoAnalyze: 'Auto-Analyze on Upload',
    autoAnalyzeDesc: 'Automatically run AI analysis when a document is uploaded.',
    language: 'Language',
    languageDesc: 'Select your preferred display language.',
    savePreferences: 'Save Preferences',
    preferencesSaved: 'Preferences saved!',
    compareDocuments: 'Compare Documents',
    compareDesc: 'Select research papers to generate an AI-powered comparative analysis.',
    selectDocuments: 'Select Documents',
    maxCompareHint: 'Select 2–5 documents',
    selectAtLeastTwo: 'Select at least 2 documents to compare',
    comparing: 'Comparing...',
    comparisonComplete: 'Comparison complete',
    comparisonFailed: 'Comparison failed',
    comparisonResults: 'Comparison Results',
    summary: 'Summary',
    commonThemes: 'Common Themes',
    conflictingFindings: 'Conflicting Findings',
    researchGaps: 'Research Gaps',
    novelOpportunities: 'Novel Opportunities',
    comparisonTable: 'Comparison Table',
    featureComparison: 'Feature Comparison',
    aiGenerated: 'AI Generated',
    heuristicResults: 'Heuristic',
    noDocumentsToCompare: 'No documents available to compare.',
    clearSelection: 'Clear',
    selected: 'selected',
    compare: 'Compare',
    recompare: 'Run again',
    noSummary: 'No summary available.',
    maxSelectionReached: 'You can compare up to 5 documents at a time',
    dimension: 'Dimension',
    paperA: 'Paper A',
    paperB: 'Paper B',
    comparison: 'Comparison',
    compareSelected: 'Compare Selected',
    newSession: 'New Session',
    navigate: 'Navigate',
    recentPapers: 'Recent Papers',
    viewAll: 'View All',
    totalPapers: 'Total Papers',
    aiAnalyses: 'AI Analyses',
    quickActions: 'Quick Actions',
    researchControlCenter: 'Research Control Center',
    researchWelcome: 'Welcome to your research environment. Monitor system state, manage knowledge ingestion, and launch focused AI analysis workflows.',
    knowledgeSources: 'Knowledge Sources',
    papersInLibrary: 'Papers in library',
    activeCollections: 'Active Collections',
    contextGroups: 'Context groups',
    neuralIndices: 'Neural Indices',
    vectorizedChunks: 'Vectorized chunks',
    systemHealth: 'System Health',
    ragEngineActive: 'RAG Engine Active',
    launchWorkflow: 'Launch Research Workflow',
    neuralIngestion: 'Neural Ingestion',
    uploadVectorize: 'Upload and vectorize new PDFs instantly',
    knowledgeLibrary: 'Knowledge Library',
    manageAnalyzeSources: 'Manage and analyze your ingested sources',
    contextManagement: 'Context Management',
    organizePapers: 'Organize papers into logical collections',
    semanticRetrieval: 'Semantic Retrieval',
    findSimilarConcepts: 'Find similar concepts across your library',
    interactiveReasoning: 'Interactive Reasoning',
    chatWithDocs: 'Chat with your documents using RAG',
    recentIngestions: 'Recent Ingestions',
    manage: 'Manage',
    scanningRepository: 'Scanning Repository...',
    libraryEmpty: 'Library Empty',
    initResearch: 'Initialize your research by uploading your first document.',
    addSource: 'Add Source',
    indexed: 'Indexed',
    ragEnabled: 'RAG Enabled',
    vectorDB: 'Vector DB',
    localInference: 'Local Inference',
  },
  Spanish: {
    dashboard: 'Panel',
    uploadPaper: 'Subir Documento',
    library: 'Biblioteca',
    semanticSearch: 'Búsqueda Semántica',
    aiChat: 'Chat IA',
    settings: 'Configuración',
    support: 'Soporte',
    researchLibrary: 'Biblioteca de Investigación',
    managePapers: 'Gestiona y accede a tus documentos de investigación.',
    uploadNew: 'Subir Nuevo',
    searchPlaceholder: 'Buscar por título, autor o palabras clave...',
    filters: 'Filtros',
    noPapers: 'No se encontraron documentos',
    noPapersHint: 'Intenta ajustar tu búsqueda o sube un nuevo documento.',
    untitled: 'Sin título',
    unknownAuthor: 'Autor desconocido',
    analyze: 'Analizar',
    viewDocument: 'Ver Documento',
    downloadPDF: 'Descargar PDF',
    deletePaper: 'Eliminar Documento',
    paperTitle: 'Título',
    authors: 'Autores',
    year: 'Año',
    uploadDate: 'Fecha de subida',
    actions: 'Acciones',
    appPreferences: 'Preferencias de la Aplicación',
    darkMode: 'Modo Oscuro',
    darkModeDesc: 'Cambia entre temas claro y oscuro.',
    compactView: 'Vista Compacta',
    compactViewDesc: 'Reduce el espaciado y el tamaño de las tarjetas.',
    autoAnalyze: 'Auto-Analizar al Subir',
    autoAnalyzeDesc: 'Ejecuta automáticamente el análisis de IA al subir un documento.',
    language: 'Idioma',
    languageDesc: 'Selecciona tu idioma de visualización preferido.',
    savePreferences: 'Guardar Preferencias',
    preferencesSaved: '¡Preferencias guardadas!',
    compareDocuments: 'Comparar Documentos',
    compareDesc: 'Seleccione documentos de investigación para generar un análisis comparativo impulsado por IA.',
    researchControlCenter: 'Centro de Control de Investigación',
    researchWelcome: 'Bienvenido a su entorno de investigación. Supervise el estado del sistema, gestione la ingesta de conocimientos y lance flujos de trabajo de análisis de IA.',
    knowledgeSources: 'Fuentes de Conocimiento',
    papersInLibrary: 'Documentos en la biblioteca',
    activeCollections: 'Colecciones Activas',
    contextGroups: 'Grupos de contexto',
    neuralIndices: 'Índices Neuronales',
    vectorizedChunks: 'Fragmentos vectorizados',
    systemHealth: 'Salud del Sistema',
    ragEngineActive: 'Motor RAG Activo',
    launchWorkflow: 'Lanzar Flujo de Trabajo',
    neuralIngestion: 'Ingesta Neuronal',
    uploadVectorize: 'Sube y vectoriza PDFs al instante',
    knowledgeLibrary: 'Biblioteca de Conocimientos',
    manageAnalyzeSources: 'Gestiona y analiza tus fuentes',
    contextManagement: 'Gestión de Contexto',
    organizePapers: 'Organiza documentos en colecciones',
    semanticRetrieval: 'Recuperación Semántica',
    findSimilarConcepts: 'Encuentra conceptos similares',
    interactiveReasoning: 'Razonamiento Interactivo',
    chatWithDocs: 'Chatea con tus documentos',
    recentIngestions: 'Ingestas Recientes',
    manage: 'Gestionar',
    scanningRepository: 'Escaneando Repositorio...',
    libraryEmpty: 'Biblioteca Vacía',
    initResearch: 'Inicia tu investigación subiendo tu primer documento.',
    addSource: 'Añadir Fuente',
    indexed: 'Indexado',
    ragEnabled: 'RAG Activado',
    vectorDB: 'DB de Vectores',
    localInference: 'Inferencia Local',
  },
  French: {
    dashboard: 'Tableau de Bord',
    uploadPaper: 'Télécharger',
    library: 'Bibliothèque',
    semanticSearch: 'Recherche Sémantique',
    aiChat: 'Chat IA',
    settings: 'Paramètres',
    support: 'Support',
    researchLibrary: 'Bibliothèque de Recherche',
    managePapers: 'Gérez et accédez à vos documents de recherche.',
    uploadNew: 'Nouveau Téléchargement',
    searchPlaceholder: 'Rechercher par titre, auteur ou mots-clés...',
    filters: 'Filtres',
    noPapers: 'Aucun document trouvé',
    noPapersHint: 'Essayez d\'ajuster votre recherche ou téléchargez un nouveau document.',
    untitled: 'Sans titre',
    unknownAuthor: 'Auteur inconnu',
    analyze: 'Analyser',
    viewDocument: 'Voir le Document',
    downloadPDF: 'Télécharger le PDF',
    deletePaper: 'Supprimer le Document',
    paperTitle: 'Titre',
    authors: 'Auteurs',
    year: 'Année',
    uploadDate: 'Date de téléchargement',
    actions: 'Actions',
    appPreferences: 'Préférences de l\'Application',
    darkMode: 'Mode Sombre',
    darkModeDesc: 'Basculer entre les thèmes clair et sombre.',
    compactView: 'Vue Compacte',
    compactViewDesc: 'Réduire l\'espacement et la taille des cartes.',
    autoAnalyze: 'Analyse Auto au Téléchargement',
    autoAnalyzeDesc: 'Lancer automatiquement l\'analyse IA lors du téléchargement.',
    language: 'Langue',
    languageDesc: 'Sélectionnez votre langue d\'affichage préférée.',
    savePreferences: 'Enregistrer les Préférences',
    preferencesSaved: 'Préférences enregistrées !',
    compareDocuments: 'Comparer les Documents',
    compareDesc: 'Analyse comparative alimentée par l\'IA.',
    researchControlCenter: 'Centre de Contrôle de Recherche',
    researchWelcome: 'Bienvenue dans votre environnement de recherche. Surveillez l\'état du système et lancez des analyses IA.',
    knowledgeSources: 'Sources de Connaissances',
    papersInLibrary: 'Documents dans la bibliothèque',
    activeCollections: 'Collections Actives',
    contextGroups: 'Groupes de contexte',
    neuralIndices: 'Indices Neuronaux',
    vectorizedChunks: 'Fragments vectorisés',
    systemHealth: 'Santé du Système',
    ragEngineActive: 'Moteur RAG Actif',
    launchWorkflow: 'Lancer le Flux de Travail',
    neuralIngestion: 'Ingestion Neuronale',
    uploadVectorize: 'Téléchargez et vectorisez des PDF instantanément',
    knowledgeLibrary: 'Bibliothèque de Connaissances',
    manageAnalyzeSources: 'Gérez et analysez vos sources',
    contextManagement: 'Gestion du Contexte',
    organizePapers: 'Organisez vos documents en collections',
    semanticRetrieval: 'Recherche Sémantique',
    findSimilarConcepts: 'Trouvez des concepts similaires',
    interactiveReasoning: 'Raisonnement Interactif',
    chatWithDocs: 'Discutez avec vos documents',
    recentIngestions: 'Ingestions Récentes',
    manage: 'Gérer',
    scanningRepository: 'Analyse du Répertoire...',
    libraryEmpty: 'Bibliothèque Vide',
    initResearch: 'Initialisez votre recherche en téléchargeant un document.',
    addSource: 'Ajouter une Source',
    indexed: 'Indexé',
    ragEnabled: 'RAG Activé',
    vectorDB: 'DB Vectorielle',
    localInference: 'Inférence Locale',
  },
  German: {
    dashboard: 'Dashboard',
    uploadPaper: 'Dokument Hochladen',
    library: 'Bibliothek',
    semanticSearch: 'Semantische Suche',
    aiChat: 'KI-Chat',
    settings: 'Einstellungen',
    support: 'Support',
    researchLibrary: 'Forschungsbibliothek',
    managePapers: 'Verwalten und greifen Sie auf Ihre hochgeladenen Forschungsarbeiten zu.',
    uploadNew: 'Neu Hochladen',
    searchPlaceholder: 'Suche nach Titel, Autor oder Schlüsselwörtern...',
    filters: 'Filter',
    noPapers: 'Keine Dokumente gefunden',
    noPapersHint: 'Passen Sie Ihre Suche an oder laden Sie ein neues Dokument hoch.',
    untitled: 'Ohne Titel',
    unknownAuthor: 'Unbekannter Autor',
    analyze: 'Analysieren',
    viewDocument: 'Dokument Ansehen',
    downloadPDF: 'PDF Herunterladen',
    deletePaper: 'Dokument Löschen',
    paperTitle: 'Titel',
    authors: 'Autoren',
    year: 'Jahr',
    uploadDate: 'Upload-Datum',
    actions: 'Aktionen',
    appPreferences: 'App-Einstellungen',
    darkMode: 'Dunkelmodus',
    darkModeDesc: 'Zwischen hellem und dunklem Thema wechseln.',
    compactView: 'Kompaktansicht',
    compactViewDesc: 'Abstände und Kartengrößen für eine dichtere Ansicht reduzieren.',
    autoAnalyze: 'Auto-Analyse beim Hochladen',
    autoAnalyzeDesc: 'Automatisch KI-Analyse beim Hochladen eines Dokuments ausführen.',
    language: 'Sprache',
    languageDesc: 'Wählen Sie Ihre bevorzugte Anzeigesprache.',
    savePreferences: 'Einstellungen Speichern',
    preferencesSaved: 'Einstellungen gespeichert!',
    compareDocuments: 'Dokumente Vergleichen',
    researchControlCenter: 'Forschungs-Kontrollzentrum',
    researchWelcome: 'Willkommen in Ihrer Forschungsumgebung. Überwachen Sie den Systemstatus.',
    knowledgeSources: 'Wissensquellen',
    papersInLibrary: 'Dokumente in der Bibliothek',
    activeCollections: 'Aktive Sammlungen',
    contextGroups: 'Kontextgruppen',
    neuralIndices: 'Neuronale Indizes',
    vectorizedChunks: 'Vektorisierte Chunks',
    systemHealth: 'Systemzustand',
    ragEngineActive: 'RAG-Engine aktiv',
    launchWorkflow: 'Workflow starten',
    neuralIngestion: 'Neuronaler Import',
    uploadVectorize: 'PDFs sofort hochladen und vektorisieren',
    knowledgeLibrary: 'Wissensdatenbank',
    manageAnalyzeSources: 'Quellen verwalten',
    contextManagement: 'Kontext-Management',
    organizePapers: 'Sammlungen organisieren',
    semanticRetrieval: 'Semantisches Abrufen',
    findSimilarConcepts: 'Ähnliche Konzepte finden',
    interactiveReasoning: 'Interaktives Schlussfolgern',
    chatWithDocs: 'Mit Dokumenten chatten',
    recentIngestions: 'Aktuelle Importe',
    manage: 'Verwalten',
    scanningRepository: 'Repository wird gescannt...',
    libraryEmpty: 'Bibliothek leer',
    initResearch: 'Erstes Dokument hochladen.',
    addSource: 'Quelle hinzufügen',
    indexed: 'Indiziert',
    ragEnabled: 'RAG aktiviert',
    vectorDB: 'Vektor-DB',
    localInference: 'Lokale Inferenz',
  },
  Hindi: {
    dashboard: 'डैशबोर्ड',
    uploadPaper: 'दस्तावेज़ अपलोड करें',
    library: 'पुस्तकालय',
    semanticSearch: 'सिमेंटिक खोज',
    aiChat: 'एआई चैट',
    settings: 'सेटिंग्स',
    support: 'सहायता',
    researchLibrary: 'अनुसंधान पुस्तकालय',
    managePapers: 'अपने शोध पत्रों को प्रबंधित करें।',
    researchControlCenter: 'अनुसंधान नियंत्रण केंद्र',
    researchWelcome: 'अपने अनुसंधान वातावरण में आपका स्वागत है।',
    knowledgeSources: 'ज्ञान स्रोत',
    papersInLibrary: 'पुस्तकालय में पत्र',
    activeCollections: 'सक्रिय संग्रह',
    contextGroups: 'संदर्भ समूह',
    neuralIndices: 'न्यूरल इंडेक्स',
    vectorizedChunks: 'वेक्टराइज्ड चंक्स',
    systemHealth: 'सिस्टम स्वास्थ्य',
    ragEngineActive: 'RAG इंजन सक्रिय',
    launchWorkflow: 'वर्कफ़्लो लॉन्च करें',
    neuralIngestion: 'न्यूरल इंजेक्शन',
    uploadVectorize: 'PDF अपलोड और वेक्टराइज करें',
    knowledgeLibrary: 'ज्ञान पुस्तकालय',
    manageAnalyzeSources: 'स्रोतों का प्रबंधन करें',
    contextManagement: 'संदर्भ प्रबंधन',
    organizePapers: 'पत्रों को व्यवस्थित करें',
    semanticRetrieval: 'सिमेंटिक रिट्रीवल',
    findSimilarConcepts: 'समान अवधारणाएं खोजें',
    interactiveReasoning: 'इंटरएक्टिव रीजनिंग',
    chatWithDocs: 'दस्तावेजों के साथ चैट करें',
    recentIngestions: 'हाल के इंजेक्शन',
    manage: 'प्रबंधित करें',
    scanningRepository: 'स्कैनिंग रिपॉजिटरी...',
    libraryEmpty: 'पुस्तकालय खाली है',
    initResearch: 'पहला दस्तावेज़ अपलोड करें।',
    addSource: 'स्रोत जोड़ें',
    indexed: 'इंडेक्स किया गया',
    ragEnabled: 'RAG सक्षम',
    vectorDB: 'वेक्टर DB',
    localInference: 'स्थानीय अनुमान',
  },
};

interface LanguageContextValue {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'English (US)',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { language, setLanguage } = useAppStore();

  const t = useCallback(
    (key: string) => {
      const dict = dictionaries[language];
      if (!dict) return key;
      return dict[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
